"""Editable scientific content for the DTS/DSS teaching atlases.
All figures are conceptual. Coefficients must be calibrated for the actual fiber.
"""

REFERENCES = {
    'raman_se': {'title': 'Hausner et al. (2011). Calibrating Single-Ended Fiber-Optic Raman Spectra Distributed Temperature Sensing Data', 'url': 'https://doi.org/10.3390/s111110859', 'evidence': 'Open-access primary research; calibration equations and differential attenuation.'},
    'raman_de': {'title': 'van de Giesen et al. (2012). Double-Ended Calibration of Fiber-Optic Raman Spectra Distributed Temperature Sensing Data', 'url': 'https://doi.org/10.3390/s120505471', 'evidence': 'Open-access primary research; forward/reverse differential-attenuation correction.'},
    'raman_code': {'title': 'Park et al. (2006). Raman-based distributed temperature sensor with simplex coding and link optimization', 'url': 'https://pure.kaist.ac.kr/en/publications/raman-based-distributed-temperature-sensor-with-simplex-coding-an/', 'evidence': 'Author institution record and abstract; coded OTDR architecture. No performance figures copied into this atlas.'},
    'raman_count': {'title': 'Tanner et al. (2011). High-resolution single-mode fiber-optic distributed Raman sensor for absolute temperature measurement using superconducting nanowire single-photon detectors', 'url': 'https://doi.org/10.1063/1.3656702', 'evidence': 'Primary research; full manuscript available from NIST: https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=910008'},
    'botda': {'title': 'Horiguchi & Tateda (1989). Optical-fiber-attenuation investigation using stimulated Brillouin scattering between a pulse and a continuous wave', 'url': 'https://doi.org/10.1364/OL.14.000408', 'evidence': 'Primary research; counter-propagating pulsed pump and CW probe.'},
    'brillouin_t': {'title': 'Kurashima, Horiguchi & Tateda (1990). Distributed-temperature sensing using stimulated Brillouin scattering in optical silica fibers', 'url': 'https://doi.org/10.1364/OL.15.001038', 'evidence': 'Primary research; Brillouin temperature sensing under controlled strain conditions.'},
    'botdr': {'title': 'Kurashima et al. (1993). Brillouin Optical-Fiber Time Domain Reflectometry', 'url': 'https://globals.ieice.org/en_transactions/communications/10.1587/e76-b_4_382/_p', 'evidence': 'Publisher and author institution records; spontaneous Brillouin return and coherent detection. No DOI is assigned in the publisher record.'},
    'dpp': {'title': 'Li et al. (2008). Differential pulse-width pair BOTDA for high spatial resolution sensing', 'url': 'https://doi.org/10.1364/OE.16.021616', 'evidence': 'Primary research; differential pulse-width measurements. DOI verified against publisher metadata.'},
    'bofda': {'title': 'Garus et al. (1996). Distributed sensing technique based on Brillouin optical-fiber frequency-domain analysis', 'url': 'https://doi.org/10.1364/OL.21.001402', 'evidence': 'Primary research; complex frequency response and spatial reconstruction.'},
    'bocda': {'title': 'Hotate & Hasegawa (2000). Measurement of Brillouin Gain Spectrum Distribution along an Optical Fiber Using a Correlation-Based Technique: Proposal, Experiment and Simulation', 'url': 'https://globals.ieice.org/en_transactions/electronics/10.1587/e83-c_3_405/_p', 'evidence': 'Publisher abstract; frequency-modulated pump/probe and local correlation peak. Publisher lists no DOI.'},
    'ofdr': {'title': 'Froggatt & Moore (1998). High-spatial-resolution distributed strain measurement in optical fiber with Rayleigh scatter', 'url': 'https://doi.org/10.1364/AO.37.001735', 'evidence': 'Primary research; local Rayleigh spectral cross-correlation.'},
    'twcotdr': {'title': 'Koyamada et al. (2009). Fiber-Optic Distributed Strain and Temperature Sensing With Very High Measurand Resolution Over Long Range Using Coherent OTDR', 'url': 'https://doi.org/10.1109/JLT.2008.928957', 'evidence': 'Primary research; frequency-controlled coherent OTDR and spectral-shift measurement.'},
}

def step(label, eq, zh, en):
    return {'label': label, 'equation': eq, 'zh': zh, 'en': en}

RAMAN_STEPS = [
    step('B0 → B1 · 发射 / Launch', 'B1(t) = sqrt(P0) a(t);  z = c (t - t0) / (2 ng)', '脉冲包络 a(t) 发射到光纤。往返时间定位 z；ng 是群折射率，t0 是系统延迟。', 'The launched pulse envelope a(t) defines the interrogation. Round-trip delay gives z; ng is the group index and t0 the system delay.'),
    step('B2S / B2AS · 散射 / Scattering', 'PS(z) ∝ (nR + 1) exp[-AS(z)];  PAS(z) ∝ nR exp[-AAS(z)]', 'nR = 1/[exp(γ/T)-1] 是声子占据数；γ = h ΔνR/kB，单位 K。A 包括相应通道的累计损耗。', 'nR = 1/[exp(γ/T)-1] is the phonon occupation; γ = h ΔνR/kB in kelvin. A includes the cumulative channel loss.'),
    step('iS / iAS · 接收 / Detection', 'iS = RS PS + bS;  iAS = RAS PAS + bAS', '先扣除背景、暗信号并校正增益；光学 WDM 分离 Stokes 与 anti-Stokes，不能用电滤波代替。', 'Subtract background/dark signals and calibrate channel gains. An optical WDM separates Stokes and anti-Stokes; electrical filtering cannot replace it.'),
    step('R → T · 解调 / Calibration', 'D(z,t) = ln[PS/PAS] + C(t) - AΔ(z);  T(z,t) = γ/D(z,t)', 'AΔ(z)=∫0^z[αAS(s)-αS(s)]ds。这里采用 Hausner 的标定符号；C 吸收通道效率差，必须由已知温度区标定。', 'AΔ(z)=∫0^z[αAS(s)-αS(s)]ds. This is the Hausner calibration convention; C absorbs channel-efficiency differences and needs known-temperature references.'),
    step('Δz / σT · 分辨率 / Resolution', 'Δzpulse ≈ c τp/(2 ng);  Δzsample = c ΔtADC/(2 ng)', '脉宽尺度与采样点间距不同；实际空间响应还受探测器带宽、滤波和编码影响。弱 anti-Stokes 通道通常主导温度不确定性。', 'Pulse scale differs from sample spacing. Detector bandwidth, filtering, and coding also affect spatial response. Weak anti-Stokes returns often dominate temperature uncertainty.'),
]

BRILLOUIN_STEPS = [
    step('B0 → Bp / Bs · 光源 / Source', 'Bp(t)=sqrt(Pp) a(t) exp(i 2πνp t);  Bs(t)=sqrt(Ps) exp(i 2πνs t)', '同源泵浦与探测支路分开。探测光经单边带调制及选边带滤波，下移到 νs=νp-Δν；两束在光纤中反向传播。', 'Pump and probe are derived from the same source. Single-sideband modulation and sideband selection create νs=νp-Δν; the waves counter-propagate.'),
    step('G(z,Δν) · 增益谱 / Gain spectrum', 'gB(z,Δν)=g0(z)/{1+[2(Δν-νB(z))/ΓB(z)]²}', '弱增益、近稳态条件下用洛伦兹线型拟合局部谱。强泵浦耗尽、脉冲瞬态及谱重叠会破坏简化模型。', 'Fit a local Lorentzian in the weak-gain, near-steady regime. Pump depletion, pulse transients, and overlapping spectra can invalidate this approximation.'),
    step('i(t,Δν) → νB(z) · 定位 / Localization', 'Gmeas(z,Δν) ≈ ln[Ps,on/Ps,off];  z = c(t-t0)/(2 ng)', '按触发时延定位，并扫描泵浦与探测频差 Δν；每个 z 拟合 Brillouin frequency shift，简称 BFS。', 'Locate by trigger delay and scan the pump-probe detuning Δν. Fit the Brillouin frequency shift (BFS) at each position.'),
    step('ΔνB · 温度与应变 / Cross-sensitivity', 'ΔνB = Cε Δεfiber + CT ΔT', '相对于参考状态的小变化模型。Cε 的单位为 Hz/单位应变（或 MHz/με），CT 为 Hz/K；不能混用单位或把单一频移当作两个未知量。', 'A small-change model relative to a reference. Cε is in Hz per unit strain (or MHz/με), CT in Hz/K. One shift cannot identify two unknowns.'),
    step('解耦 / Compensation', 'Δεfiber=(ΔνB-CT ΔT)/Cε;  ΔT=(ΔνB-Cε Δεfiber)/CT', '应变测量需要独立温度信息；测温需要已知或隔离的光纤应变。光缆热膨胀与约束会改变有效标定。', 'Strain sensing requires independent temperature information; thermometry requires known or isolated fiber strain. Cable expansion and constraint alter the effective calibration.'),
]

RAYLEIGH_STEPS = [
    step('B0 → B1 / BL · 分光 / Split', 'ν(t)=ν0+κt;  B1 ∝ exp[i2π∫ν(t)dt];  BL is the reference field', '扫频光分为测量与参考支路；辅助不等臂 MZI 提供扫频时钟。κ 为实际光频扫描速率。', 'Split the swept source into measurement and reference branches. An auxiliary unequal-arm MZI supplies the sweep clock; κ is the actual optical-frequency sweep rate.'),
    step('B2 + BL → i · 拍频 / Beat', 'i(t) ∝ 2 Re[B2(t) BL*(t)];  fb=κ τrel', '回波与参考光相干混频。τrel 是相对参考支路的延迟，需要零点标定，不能默认全部距离从光源开始。', 'Mix the return with the reference. τrel is the delay relative to that arm; calibrate the distance origin rather than assuming it begins at the laser.'),
    step('i → r(z) · 空间变换 / Spatial transform', 'z-zref = c fb/(2 ng κ);  Δzideal ≈ c/(2 ng Bν)', '按实际光频重采样后作傅里叶变换。Bν 是光频扫描带宽；上述理想分辨率不等于应变标距。', 'Resample on the measured optical-frequency grid before Fourier transformation. Bν is the optical scan bandwidth; ideal reflectometric resolution differs from the strain gauge length.'),
    step('r0 / r1 → q · 指纹相关 / Fingerprint correlation', 'δν(z)=argmaxδ Corr[S0(z,ν), S1(z,ν+δ)];  q=-δν/ν0', '在相同窗口内比较参考与当前瑞利指纹；δν 是当前谱相对参考的有符号光频移。通常拉伸导致红移 δν<0，因此 q>0；须按实际相关实现核对符号。', 'Compare reference and current Rayleigh fingerprints in matching windows. δν is the signed current-minus-reference optical-frequency shift. Tension usually gives a red shift δν<0, hence q>0; verify the sign in the actual correlation implementation.'),
    step('q → Δε / ΔT · 解耦 / Compensation', 'q = Kε Δεfiber + KT ΔT', 'Kε、KT 按此符号约定实测标定；普通硅纤中通常为正。温度和应变同时变化时需第二个独立观测。', 'Calibrate Kε and KT under this sign convention; they are usually positive for ordinary silica fiber. Simultaneous temperature and strain changes require a second independent observation.'),
]

def route(id, name, en, mechanism, topology, observable, obs_en, summary, sum_en, components, steps, limits, limits_en, refs):
    return dict(id=id, name=name, en=en, mechanism=mechanism, topology=topology, observable=observable, obs_en=obs_en, summary=summary, sum_en=sum_en, components=components, steps=steps, limits=limits, limits_en=limits_en, refs=refs)

RAMAN_COMPONENTS = ['ld','ld_driver','awg','im','cir','fiber','wdm','apd','adc','bath','rtd','computer']
BRILLOUIN_COMPONENTS = ['nll','iso','splitter','im','iq','bpf','edfa','pc','cir','fiber','pd','adc','dds','bias','computer']
RAYLEIGH_COMPONENTS = ['tls','splitter','coupler2_dk','cir','fiber','delay','pc','bpd','adc','computer']

DTS = [
    route('DTS01','单端拉曼 OTDR','Single-ended Raman OTDR','Raman','raman','Stokes / anti-Stokes 强度比','Stokes / anti-Stokes intensity ratio','从一端发射脉冲、接收两条拉曼谱带；用参考温度区与差分衰减校正获得沿纤温度。','Launch and receive from one end; calibrate the Raman ratio using known-temperature references and differential attenuation.',RAMAN_COMPONENTS,RAMAN_STEPS,'熔接、弯曲及连接器会产生局部差分损耗；单端标定的损耗模型不能自动覆盖所有变化。','Splices, bends, and connectors create local differential losses; a single-ended loss model cannot automatically cover every change.',['raman_se']),
    route('DTS02','双端拉曼 OTDR','Double-ended Raman OTDR','Raman','raman_double','双向强度比与差分衰减','Forward/reverse ratios and differential attenuation','光纤两端接入光开关，交替从 A、B 两端测量；先统一物理坐标，再联合标定。','Connect both ends through an optical switch and interrogate alternately; map both traces to the same physical coordinate before joint calibration.',RAMAN_COMPONENTS+['switch'],RAMAN_STEPS[:3]+[
        step('A / B → z · 双端坐标 / Coordinates','zA=c(tA-t0A)/(2ng);  z=L-c(tB-t0B)/(2ng)','B 端迹线需要反转到 A 端的 z 坐标；两端时延零点和有效纤长 L 分别标定。','Reverse the B-end trace into the A-end coordinate; calibrate both delay origins and the effective fiber length L.'),
        step('DA / DB · 联合标定 / Joint calibration','ln(RA)+CA=γ/T+AΔ(0,z);  ln(RB)+CB=γ/T+AΔ(z,L)','若传递互易、两端增益已校准且温度在轮询间稳定，则两式平均得到 γ/T+AΔ(0,L)/2；仍需参考温度区确定常数。','For reciprocal transfer, calibrated end gains, and temperature stable during switching, averaging yields γ/T+AΔ(0,L)/2; reference temperatures are still needed.'),
        step('校正边界 / Limits of correction','T=γ/{[ln(RA)+CA+ln(RB)+CB]/2-AΔ(0,L)/2}','双端校正针对沿程差分损耗，不会消除未知时间变化、非互易增益、饱和或参考温区误差。','Double-ended correction addresses distributed differential loss; it cannot remove unknown temporal changes, non-reciprocal gains, saturation, or bad references.')
    ],'需要两端可达及稳定的双向坐标映射；两端交替测量的时间错位对快速过程尤其重要。','Both ends must be accessible and spatially aligned; interleaved acquisitions can alias rapid thermal changes.',['raman_de']),
    route('DTS03','编码拉曼 OTDR','Coded Raman OTDR','Raman','raman_coded','解码后的两通道脉冲响应','Decoded dual-channel impulse responses','保持拉曼测温原理，用多脉冲编码累积能量，再恢复单脉冲响应。','Keep the Raman thermometry principle, accumulate energy with coded pulses, and recover the single-pulse response.',RAMAN_COMPONENTS+['fpga'],[
        step('a → c · 编码发射 / Coded launch','a(t)=Σk ck p(t-kTc)','ck 是实际非负发射码；双极性数学码需通过互补或分组采集实现，不能直接发射负光功率。','ck is a realizable non-negative optical code. Bipolar mathematical codes require complementary/grouped acquisitions; negative optical power is impossible.'),
        step('yS / yAS · 线性测量 / Linear acquisition','yj = C hj + ηj;  j ∈ {S,AS}','C 是由实际发射序列构造的编码矩阵；两通道共享时序，但噪声和增益不同。','C is the matrix of actual launched codes; the two channels share timing but have different noise and gains.'),
        step('y → h · 解码 / Decode','ĥj = D yj;  D C ≈ I','D 是匹配码族的解码算子；先解码两条通道，再扣背景、求比值和标定温度。','D is the decoder for the selected code family. Decode both channels before background subtraction, ratio formation, and thermometry.'),
        RAMAN_STEPS[3], RAMAN_STEPS[4]
    ],'编码增益依赖码长、噪声、脉冲非线性与解码条件；不能把码长直接当作空间分辨率或保证的信噪比提升。','Coding benefit depends on code length, noise, pulse nonlinearity, and decoder conditions; code length does not itself set spatial resolution or guarantee SNR gain.',['raman_code','raman_se']),
    route('DTS04','光子计数拉曼 OTDR','Photon-counting Raman OTDR','Raman','raman_count','Stokes / anti-Stokes 到达时间直方图','Stokes / anti-Stokes arrival-time histograms','以单光子探测器和时间标记器替代模拟接收链；保留拉曼比值与标定关系。','Replace the analog receiver with single-photon detectors and time tagging; retain Raman-ratio calibration.', ['ld','ld_driver','awg','im','cir','fiber','wdm','spad','timetag','bath','rtd','computer'],[
        step('发射 → 计数 / Launch to counts','NS(z), NAS(z) = counts in calibrated delay bins','以同步触发建立到达时间直方图；先扣暗计数与背景。时间箱宽是采样间距，不自动等于分辨率。','Build delay histograms against the launch trigger; subtract dark/background counts. Bin width sets sampling, not automatically spatial resolution.'),
        step('计数 → 功率代理 / Counts to power proxy','Pj ∝ (Nj-bj)/(ηj tm);  j ∈ {S,AS}','ηj 包括光路透过率与探测效率，tm 是累计时间；需在线性低计数区使用，检查死时间与堆积。','ηj includes optical throughput and detector efficiency; tm is integration time. Operate in the low-count linear regime and check dead time and pile-up.'),
        RAMAN_STEPS[3],
        step('统计不确定性 / Counting uncertainty','σ²lnR ≈ 1/NS + 1/NAS;  σT ≈ (T²/γ) σlnR','仅适用于独立泊松计数、背景可忽略、标定参数固定。实际还需传播背景、效率及损耗标定误差。','Applies only to independent Poisson counts, negligible background, and fixed calibration. Real uncertainty also includes background, efficiency, and attenuation calibration.'),
        step('时间尺度 / Timing scales','Δzpulse ≈ c τp/(2ng);  Δzbin = c Δtbin/(2ng)','脉宽尺度与直方图箱间距不同；实际响应还受探测器抖动、光纤色散和计数处理影响。','Pulse scale differs from histogram bin spacing. Detector jitter, fiber dispersion, and counting processing also affect the response.')
    ],'SNSPD 与 SPAD 不是同一器件；示意图以单光子接收功能为概括，引用实例采用需要低温系统的 SNSPD。','SNSPD and SPAD are different detectors. The functional schematic represents single-photon reception; the cited experiment used cryogenic SNSPDs.',['raman_count','raman_se']),
    route('DTS05','布里渊 BOTDA 测温','Brillouin BOTDA thermometry','Brillouin','botda','局部布里渊频移 BFS','Local Brillouin frequency shift','通过泵浦-探测频差扫描获得局部增益谱；在应变已知或隔离时反演温度。','Scan pump-probe detuning to obtain local gain spectra; infer temperature only when strain is known or isolated.',BRILLOUIN_COMPONENTS,BRILLOUIN_STEPS,'BFS 同时对温度与应变敏感；松套管不能保证所有工况下完全无应变。还须校准实际光缆热响应。','BFS responds to temperature and strain. A loose tube does not guarantee zero strain under every condition; actual cable thermal response needs calibration.',['brillouin_t','botda']),
    route('DTS06','瑞利 OFDR 相对测温','Rayleigh OFDR relative thermometry','Rayleigh','ofdr','相对参考状态的局部谱移','Local spectral shift relative to a reference','用扫频干涉和局部瑞利指纹相关测量温度变化；已知参考温度及应变后才可恢复温度。','Use swept interferometry and local fingerprint correlation for temperature change; known reference temperature and strain are needed to recover temperature.',RAYLEIGH_COMPONENTS,RAYLEIGH_STEPS,'不是免标定的绝对温度计；大谱移、相干衰落和扫频期间状态变化会使相关失效。','This is not calibration-free absolute thermometry. Large shifts, fading, and state changes during a sweep can defeat correlation.',['ofdr']),
]

DSS = [
    route('DSS01','自发布里渊 BOTDR','Spontaneous Brillouin BOTDR','Brillouin','botdr','自发布里渊回波频谱中心','Center of the spontaneous Brillouin spectrum','单端发射脉冲；回波与同源频移本振相干检测，逐位置恢复 BFS。','Launch from one end and coherently detect the return with a frequency-shifted same-source local oscillator to recover BFS by position.', ['nll','splitter','im','iq','bias','dds','edfa','cir','fiber','bpf','bpd','adc','awg','computer'],[
        step('B0 → Bp / BL · 分支 / Branches','Bp(t)=sqrt(Pp)a(t)exp(i2πν0t);  BL(t)=sqrt(PL)exp(i2πνLOt)','一支生成脉冲，一支保留为本振；不需要从远端注入连续探测光。','One arm is pulsed and the other retained as a local oscillator; no continuous probe is injected at the far end.'),
        step('BBS + BL → i · 相干接收 / Coherent reception','νLO=ν0-νoffset;  fIF ≈ |νoffset-νB(z)|','Stokes 回波约为 ν0-νB；本振经单边带频移与滤波，把 GHz 量级布里渊光频差转到接收器带宽内。频移量与增减方向需标定。','The Stokes return is near ν0-νB. Shift/filter the LO sideband to place the GHz-scale Brillouin beat inside the receiver bandwidth; calibrate the offset and its sign.'),
        step('时窗 → z · 定位 / Localization','z=c(t-t0)/(2ng);  Δzpulse ≈ cτp/(2ng)','按往返时延分窗，估计每窗频谱。脉宽与声子寿命会影响空间响应和谱宽。','Window by round-trip delay and estimate each spectrum. Pulse duration and phonon lifetime affect spatial response and linewidth.'),
        BRILLOUIN_STEPS[3], BRILLOUIN_STEPS[4]
    ],'自发散射信号弱，通常需要平均与扫频/谱估计；单端可达不意味着温度与应变自动分离。','Spontaneous returns are weak and usually require averaging and spectral estimation; single-ended access does not automatically separate strain and temperature.',['botdr']),
    route('DSS02','受激布里渊 BOTDA','Stimulated Brillouin BOTDA','Brillouin','botda','局部增益谱与 BFS','Local gain spectrum and BFS','泵浦脉冲与连续探测光反向传播，在逐位置增益谱中估计应变。','A pump pulse and CW probe counter-propagate; local gain spectra are converted to strain after compensation.',BRILLOUIN_COMPONENTS,BRILLOUIN_STEPS,'通常需光纤两端可达或形成回路；泵浦耗尽、非局部效应、偏振与温度交叉敏感均须控制。','Normally needs access to both ends or a loop. Control depletion, non-local effects, polarization, and temperature cross-sensitivity.',['botda']),
    route('DSS03','差分脉宽对 DPP-BOTDA','Differential pulse-width pair BOTDA','Brillouin','dpp', '两条增益迹线之差','Difference of two gain traces','用共同起点、不同宽度的两组脉冲测量，差分提取短尾段的局部贡献。','Acquire two pulses with a common leading edge and different widths; their difference isolates the contribution of the short trailing interval.',BRILLOUIN_COMPONENTS+['awg'],[
        BRILLOUIN_STEPS[0],
        step('G1 / G2 → Gdiff · 差分 / Difference','Gdiff(z,Δν)=Gτ1(z,Δν)-Gτ2(z,Δν);  τ1>τ2','两组迹线先做时间对齐和功率归一；相同前沿条件下差值提取长脉冲尾段。','Align timing and normalize power first; under matched leading-edge conditions, subtraction isolates the longer pulse tail.'),
        step('尾段尺度 / Tail-interval scale','Δzideal ≈ c(τ1-τ2)/(2ng)','这是理想差分门宽尺度；实际受脉冲边沿、接收带宽、声学瞬态与减法噪声限制。','This is the ideal differential gate scale, limited in practice by pulse edges, receive bandwidth, acoustic transients, and subtraction noise.'),
        BRILLOUIN_STEPS[3], BRILLOUIN_STEPS[4]
    ],'不能把小脉宽差当作无条件空间分辨率；两次采集中的状态变化会产生差分伪影。','A small width difference does not guarantee resolution; changes between acquisitions can create subtraction artifacts.',['dpp']),
    route('DSS04','布里渊频域 BOFDA','Brillouin optical frequency-domain analysis','Brillouin','bofda','小信号复传递函数 H(fm,Δν)','Small-signal complex transfer H(fm,Δν)','连续泵浦以小幅正弦强度调制；测量探测光响应的幅度与相位，再转为空间响应。','Apply small sinusoidal intensity modulation to a CW pump; measure probe amplitude and phase, then reconstruct space.',BRILLOUIN_COMPONENTS+['vna'],[
        step('Bp · 小信号调制 / Small-signal modulation','Pp(t)=P0[1+m cos(2πfmt)];  m≪1','扫描电学调制频率 fm，同时扫描光学泵浦-探测频差 Δν；两种频率不能混淆。','Scan the electrical modulation fm and the optical pump-probe detuning Δν; these are different frequency axes.'),
        step('H · 复响应 / Complex response','H(fm,Δν)=δPs(fm,Δν)/δPp(fm)','VNA 或同步锁相测量相对发射调制的幅度与相位，不能仅测平均光强。','A VNA or synchronous lock-in measures amplitude and phase relative to the pump modulation; mean intensity alone is insufficient.'),
        step('H → h(z) · 空间反演 / Spatial reconstruction','h(τ,Δν)=IFTfm[H];  z=cτ/(2ng)','延迟零点取决于系统参考；Δz≈c/(2ng Bm)，无歧义距离≈c/(2ng δfm)，均为理想尺度。','Calibrate the delay origin. Δz≈c/(2ng Bm) and unambiguous range≈c/(2ng δfm) are ideal scales.'),
        BRILLOUIN_STEPS[3], BRILLOUIN_STEPS[4]
    ],'傅里叶反演需有限带宽窗函数、参考去嵌入及声学响应考虑；不是把 BOTDA 的时间轴简单换个名字。','Reconstruction needs bandwidth/window treatment, reference de-embedding, and acoustic-response considerations; it is not merely a renamed BOTDA time axis.',['bofda']),
    route('DSS05','布里渊相关域 BOCDA','Brillouin optical correlation-domain analysis','Brillouin','bocda','相关峰附近的局部增益谱','Local gain spectrum near a correlation peak','共同频率调制的泵浦与探测光在特定位置形成频差匹配区；移动相关峰扫描光纤。','Common frequency modulation creates a localized pump-probe match; move the correlation peak to scan the fiber.',BRILLOUIN_COMPONENTS+['delay','fm_driver'],[
        step('B0 → Bp / Bs · 共同调制 / Common modulation','ν(t)=ν0+Δf sin(2πfmt);  νs(t)=ν(t)-Δν','对同源泵浦与探测施加相关频率调制，支路延迟决定相关峰位置。','Apply correlated FM to same-source pump/probe waves; the arm delay sets the correlation-peak position.'),
        step('局部相关 / Local correlation','δνlocal(z,t)=Δν+ν(t-τp(z))-ν(t-τs(z))','当两路调制在某位置对齐，局部频差较稳定；其他位置谱展宽形成背景。','Where modulation delays match, local detuning is stable; mismatched positions give broadened background.'),
        step('峰距 / Peak spacing','dpeak≈c/(2ngfm);  Δz ∝ 1/(fm Δf)','这是正弦 FM 实现的峰距及分辨率趋势；比例系数取决于线宽、调制与门控，须依据实际实现计算。','For sinusoidal FM this gives peak spacing and a resolution trend; prefactors depend on linewidth, modulation, and gating.'),
        BRILLOUIN_STEPS[3], BRILLOUIN_STEPS[4]
    ],'多个相关峰、背景增益与扫描位置标定决定可用范围；通常需要两端接入，不能沿用 OTDR 的脉冲时延公式定位。','Multiple correlation peaks, background gain, and position calibration limit the usable range. Usually double-ended; pulse time-of-flight is not the localization rule.',['bocda']),
    route('DSS06','瑞利 OFDR 应变测量','Rayleigh OFDR strain sensing','Rayleigh','ofdr','相对参考状态的局部谱移','Local spectral shift relative to a reference','扫频干涉给出距离，再用局部瑞利谱相关估计轴向光纤应变变化。','Swept interferometry establishes distance; local Rayleigh correlation then estimates changes in axial fiber strain.',RAYLEIGH_COMPONENTS,RAYLEIGH_STEPS,'需要保存参考指纹、选择标距并校准温度；局部相关失败时应标记缺测，不能自动填成可靠应变。','Retain reference fingerprints, choose a gauge length, and calibrate temperature. Mark failed correlation as missing rather than inventing reliable strain.',['ofdr']),
    route('DSS07','频率扫描相干 OTDR','Frequency-scanned coherent OTDR','Rayleigh','twcotdr','每个距离窗的瑞利频谱移','Rayleigh spectral shift per distance window','对多个稳定光频分别发射脉冲，用时延定位、频率扫描构建局部指纹，再相关求应变。','Launch pulses at multiple stabilized frequencies; use delay for location and the frequency scan for local fingerprint correlation.', ['nll','splitter','im','iq','cir','fiber','bpd','adc','awg','dds','computer'],[
        step('B0 → Bp / BL · 逐频发射 / Frequency stepping','νm=ν0+m δν;  Bp,m(t)=a(t)exp(i2πνmt)','光频在各次脉冲之间步进，单次脉冲内保持近似稳定；不同于连续扫频 OFDR。','Step frequency between launches and keep it approximately stable within each pulse; this differs from continuously swept OFDR.'),
        step('i(t,νm) → S(z,νm) · 指纹 / Fingerprint','z=c(t-t0)/(2ng);  S(z,νm)=local Rayleigh signature','空间位置由脉冲时延给出；光频轴用于局部指纹相关，不用于 OFDR 距离拍频公式。','Pulse delay gives position. The optical-frequency axis is for local fingerprint correlation, not OFDR beat-frequency ranging.'),
        RAYLEIGH_STEPS[3], RAYLEIGH_STEPS[4],
        step('补偿后应变 / Compensated strain','Δεfiber=(q-KT ΔT)/Kε','同样需要温度补偿与参考状态；整个频率扫描期间应变变化会破坏准静态假设。','Temperature compensation and a reference remain necessary; changes during the full frequency scan break the quasi-static assumption.')
    ],'频扫相干 OTDR 的谱移法与常见 DAS 相位法不同；扫描时长、频率稳定度和相关窗限制动态测量。','Spectral-shift coherent OTDR differs from common phase-based DAS. Scan duration, frequency stability, and correlation windows constrain dynamic measurements.',['twcotdr']),
]

# New functions have conceptual illustrations, not mislabeled manufacturer photos.
SPECIAL_COMPONENTS = [
    dict(key='wdm', name='拉曼双带 WDM / 滤波模块', en='Dual-band Raman WDM / filters', abbr='WDM', role='将回波分到 Stokes 与 anti-Stokes 通道，并抑制强瑞利光及泵浦泄漏。', role_en='Separate Stokes/anti-Stokes bands and reject strong Rayleigh/pump leakage.', note='需按激光波长配置两条拉曼谱带；普通 1550 nm 带通滤波器不能替代。', note_en='Match both Raman bands to the laser; an ordinary 1550 nm bandpass is not a substitute.', eq='PS=Pback|HS|²; PAS=Pback|HAS|²'),
    dict(key='apd', name='双通道模拟弱光接收', en='Dual-channel analog weak-light receiver', abbr='APD / PD + TIA', role='分别接收两条拉曼谱带并作同步采样。', role_en='Detect both Raman bands and sample synchronously.', note='示意的是接收功能；Si / InGaAs、增益、带宽与谱带匹配须另行选型。', note_en='Functional illustration only; select Si/InGaAs, gain, bandwidth, and spectral coverage separately.', eq='ij=Rj Pj+bj'),
    dict(key='switch', name='双端测量光开关', en='Optical switch for double-ended interrogation', abbr='SW', role='在 A、B 两个光纤端口之间轮询发射与回波接收。', role_en='Alternate launch and reception between fiber ends A and B.', note='记录切换时间及两端损耗；不是两个端口同时发射。', note_en='Record switching time and end losses; this is sequential interrogation.', eq='port(t) ∈ {A,B}'),
    dict(key='bath', name='已知温度参考区', en='Known-temperature reference section', abbr='REF bath', role='提供 γ、C 和差分衰减等标定量所需的已知温度区段。', role_en='Provide known-temperature sections to calibrate γ, C, and attenuation.', note='参考区长度、温度均匀性、热平衡与独立验证区都需要检查。', note_en='Check section length, uniformity, equilibrium, and independent validation.', eq='T(z ∈ Zref)=Tref'),
    dict(key='rtd', name='独立参考温度计', en='Independent reference thermometer', abbr='RTD', role='测量参考区温度，并记录其准确度和响应时间。', role_en='Measure reference temperature with documented accuracy and response.', note='DTS 与参考温度计时间需同步；不能用 DTS 自身输出作为独立校准真值。', note_en='Synchronize timing; DTS output cannot serve as its own independent calibration truth.', eq='Tref ± uref'),
    dict(key='spad', name='单光子探测接收模块', en='Single-photon detection module', abbr='SNSPD / SPAD', role='把弱拉曼光转为离散计数事件。', role_en='Convert weak Raman photons into count events.', note='两种探测器实现不同；本文引文使用 SNSPD，需低温系统。此图为功能示意。', note_en='The detector technologies differ; the cited SNSPD experiment needs cryogenic cooling. This is a functional illustration.', eq='Nj≈ηj Φj tm+bj'),
    dict(key='timetag', name='时间相关计数 / 标记器', en='Time-correlated counter / tagger', abbr='TCSPC / TDC', role='以发射触发为零点统计回波到达时间。', role_en='Histogram return arrival times relative to launch triggers.', note='时间箱、抖动、死时间及堆积均影响真实分辨率与温度误差。', note_en='Bin size, jitter, dead time, and pile-up affect resolution and temperature error.', eq='z=c(tarrival-t0)/(2ng)'),
    dict(key='vna', name='复响应同步测量', en='Synchronous complex-response measurement', abbr='VNA / lock-in', role='驱动泵浦小信号调制，并记录探测光响应的幅度与相位。', role_en='Drive small-signal pump modulation and record probe amplitude/phase.', note='BOFDA 的电调制频率 fm 与光频差 Δν 是独立扫描轴。', note_en='BOFDA modulation fm and optical detuning Δν are independent scan axes.', eq='H=|H| exp(iφ)'),
    dict(key='fm_driver', name='相关域光频调制驱动', en='Correlation-domain optical FM driver', abbr='FM driver', role='对同源光施加可控频率调制，并配合延迟和门控定位相关峰。', role_en='Apply controlled common FM and coordinate delay/gating for correlation peaks.', note='实际光频调制幅度需测量；电流驱动电压不直接等于光频。', note_en='Measure actual optical FM depth; drive voltage is not optical frequency.', eq='ν(t)=ν0+Δf sin(2πfmt)'),
]

TITLES = {
    'dts': ('DTS 温度传感原理图册', 'DTS temperature-sensing atlas', '拉曼强度比、布里渊频移与瑞利指纹：六类代表性路线。', 'Six representative routes using Raman ratios, Brillouin shifts, and Rayleigh fingerprints.'),
    'dss': ('DSS 应变传感原理图册', 'DSS strain-sensing atlas', '时域、频域与相关域：七类代表性布里渊与瑞利路线。', 'Seven representative Brillouin and Rayleigh routes across time, frequency, and correlation domains.'),
}
