"""Explicit TeX equivalents of the existing equations; no heuristic division parsing."""
EQUATIONS = {
 'B1(t) = sqrt(P0) a(t);  z = c (t - t0) / (2 ng)':r'B_1(t)=\sqrt{P_0}\,a(t),\qquad z=\frac{c(t-t_0)}{2n_g}',
 'PS(z) ∝ (nR + 1) exp[-AS(z)];  PAS(z) ∝ nR exp[-AAS(z)]':r'\begin{aligned}P_{\mathrm S}(z)&\propto(n_R+1)e^{-A_{\mathrm S}(z)},&P_{\mathrm{AS}}(z)&\propto n_R e^{-A_{\mathrm{AS}}(z)},\\n_R&=\frac1{e^{\gamma/T}-1},&\gamma&=\frac{h\Delta\nu_R}{k_B}.\end{aligned}',
 'iS = RS PS + bS;  iAS = RAS PAS + bAS':r'i_{\mathrm S}=\mathcal R_{\mathrm S}P_{\mathrm S}+b_{\mathrm S},\qquad i_{\mathrm{AS}}=\mathcal R_{\mathrm{AS}}P_{\mathrm{AS}}+b_{\mathrm{AS}}',
 'D(z,t) = ln[PS/PAS] + C(t) - AΔ(z);  T(z,t) = γ/D(z,t)':r'\begin{aligned}D(z,t)&=\ln\!\frac{P_{\mathrm S}}{P_{\mathrm{AS}}}+C(t)-A_\Delta(z),\\T(z,t)&=\frac{\gamma}{D(z,t)},\\A_\Delta(z)&=\int_0^z[\alpha_{\mathrm{AS}}(s)-\alpha_{\mathrm S}(s)]\,\mathrm ds.\end{aligned}',
 'Δzpulse ≈ c τp/(2 ng);  Δzsample = c ΔtADC/(2 ng)':r'\Delta z_{\mathrm{pulse}}\simeq\frac{c\tau_p}{2n_g},\qquad\Delta z_{\mathrm{sample}}=\frac{c\Delta t_{\mathrm{ADC}}}{2n_g}',
 'zA=c(tA-t0A)/(2ng);  z=L-c(tB-t0B)/(2ng)':r'z_A=\frac{c(t_A-t_{0A})}{2n_g},\qquad z=L-\frac{c(t_B-t_{0B})}{2n_g}',
 'ln(RA)+CA=γ/T+AΔ(0,z);  ln(RB)+CB=γ/T+AΔ(z,L)':r'\begin{aligned}\ln R_A+C_A&=\frac{\gamma}{T}+A_\Delta(0,z),\\\ln R_B+C_B&=\frac{\gamma}{T}+A_\Delta(z,L),\\A_\Delta(a,b)&=\int_a^b[\alpha_{\mathrm{AS}}(s)-\alpha_{\mathrm S}(s)]\,\mathrm ds.\end{aligned}',
 'T=γ/{[ln(RA)+CA+ln(RB)+CB]/2-AΔ(0,L)/2}':r'T=\frac{\gamma}{\frac12(\ln R_A+C_A+\ln R_B+C_B)-\frac12 A_\Delta(0,L)}',
 'a(t)=Σk ck p(t-kTc)':r'a(t)=\sum_k c_k p(t-kT_c)',
 'yj = C hj + ηj;  j ∈ {S,AS}':r'\mathbf y_j=\mathbf C\mathbf h_j+\boldsymbol\eta_j,\qquad j\in\{\mathrm S,\mathrm{AS}\}',
 'ĥj = D yj;  D C ≈ I':r'\widehat{\mathbf h}_j=\mathbf D\mathbf y_j,\qquad\mathbf D\mathbf C\simeq\mathbf I',
 'NS(z), NAS(z) = counts in calibrated delay bins':r'N_{\mathrm S}(z),\ N_{\mathrm{AS}}(z)\quad\text{counts in calibrated delay bins}',
 'Pj ∝ (Nj-bj)/(ηj tm);  j ∈ {S,AS}':r'P_j\propto\frac{N_j-b_j}{\eta_j t_m},\qquad j\in\{\mathrm S,\mathrm{AS}\}',
 'σ²lnR ≈ 1/NS + 1/NAS;  σT ≈ (T²/γ) σlnR':r'\sigma_{\ln R}^2\simeq\frac1{N_{\mathrm S}}+\frac1{N_{\mathrm{AS}}},\qquad\sigma_T\simeq\frac{T^2}{\gamma}\sigma_{\ln R}',
 'Δzpulse ≈ c τp/(2ng);  Δzbin = c Δtbin/(2ng)':r'\Delta z_{\mathrm{pulse}}\simeq\frac{c\tau_p}{2n_g},\qquad\Delta z_{\mathrm{bin}}=\frac{c\Delta t_{\mathrm{bin}}}{2n_g}',
 'Bp(t)=sqrt(Pp) a(t) exp(i 2πνp t);  Bs(t)=sqrt(Ps) exp(i 2πνs t)':r'\begin{aligned}B_p(t)&=\sqrt{P_p}\,a(t)e^{i2\pi\nu_p t},\\B_s(t)&=\sqrt{P_s}\,e^{i2\pi\nu_s t},\qquad\nu_s=\nu_p-\Delta\nu.\end{aligned}',
 'gB(z,Δν)=g0(z)/{1+[2(Δν-νB(z))/ΓB(z)]²}':r'g_B(z,\Delta\nu)=\frac{g_0(z)}{1+\left[\frac{2(\Delta\nu-\nu_B(z))}{\Gamma_B(z)}\right]^2}',
 'Gmeas(z,Δν) ≈ ln[Ps,on/Ps,off];  z = c(t-t0)/(2 ng)':r'G_{\mathrm{meas}}(z,\Delta\nu)\simeq\ln\!\frac{P_{s,\mathrm{on}}}{P_{s,\mathrm{off}}},\qquad z=\frac{c(t-t_0)}{2n_g}',
 'ΔνB = Cε Δεfiber + CT ΔT':r'\Delta\nu_B=C_\varepsilon\Delta\varepsilon_{\mathrm{fiber}}+C_T\Delta T',
 'Δεfiber=(ΔνB-CT ΔT)/Cε;  ΔT=(ΔνB-Cε Δεfiber)/CT':r'\Delta\varepsilon_{\mathrm{fiber}}=\frac{\Delta\nu_B-C_T\Delta T}{C_\varepsilon},\qquad\Delta T=\frac{\Delta\nu_B-C_\varepsilon\Delta\varepsilon_{\mathrm{fiber}}}{C_T}',
 'ν(t)=ν0+κt;  B1 ∝ exp[i2π∫ν(t)dt];  BL is the reference field':r'\nu(t)=\nu_0+\kappa t,\qquad B_1(t)\propto\exp\!\left[i2\pi\int^t\nu(s)\,\mathrm ds\right],\qquad B_L:\text{ reference field}',
 'i(t) ∝ 2 Re[B2(t) BL*(t)];  fb=κ τrel':r'i(t)\propto2\operatorname{Re}[B_2(t)B_L^*(t)],\qquad f_b=\kappa\tau_{\mathrm{rel}}',
 'z-zref = c fb/(2 ng κ);  Δzideal ≈ c/(2 ng Bν)':r'z-z_{\mathrm{ref}}=\frac{cf_b}{2n_g\kappa},\qquad\Delta z_{\mathrm{ideal}}\simeq\frac{c}{2n_g B_\nu}',
 'δν(z)=argmaxδ Corr[S0(z,ν), S1(z,ν+δ)];  q=-δν/ν0':r'\delta\nu(z)=\underset{\delta}{\operatorname{arg\,max}}\operatorname{Corr}[S_0(z,\nu),S_1(z,\nu+\delta)],\qquad q=-\frac{\delta\nu}{\nu_0}',
 'q = Kε Δεfiber + KT ΔT':r'q=K_\varepsilon\Delta\varepsilon_{\mathrm{fiber}}+K_T\Delta T',
 'Bp(t)=sqrt(Pp)a(t)exp(i2πν0t);  BL(t)=sqrt(PL)exp(i2πνLOt)':r'B_p(t)=\sqrt{P_p}\,a(t)e^{i2\pi\nu_0t},\qquad B_L(t)=\sqrt{P_L}\,e^{i2\pi\nu_{\mathrm{LO}}t}',
 'νLO=ν0-νoffset;  fIF ≈ |νoffset-νB(z)|':r'\nu_{\mathrm{LO}}=\nu_0-\nu_{\mathrm{offset}},\qquad f_{\mathrm{IF}}\simeq\left|\nu_{\mathrm{offset}}-\nu_B(z)\right|',
 'z=c(t-t0)/(2ng);  Δzpulse ≈ cτp/(2ng)':r'z=\frac{c(t-t_0)}{2n_g},\qquad\Delta z_{\mathrm{pulse}}\simeq\frac{c\tau_p}{2n_g}',
 'Gdiff(z,Δν)=Gτ1(z,Δν)-Gτ2(z,Δν);  τ1>τ2':r'G_{\mathrm{diff}}(z,\Delta\nu)=G_{\tau_1}(z,\Delta\nu)-G_{\tau_2}(z,\Delta\nu),\qquad\tau_1>\tau_2',
 'Δzideal ≈ c(τ1-τ2)/(2ng)':r'\Delta z_{\mathrm{ideal}}\simeq\frac{c(\tau_1-\tau_2)}{2n_g}',
 'Pp(t)=P0[1+m cos(2πfmt)];  m≪1':r'P_p(t)=P_0[1+m\cos(2\pi f_mt)],\qquad m\ll1',
 'H(fm,Δν)=δPs(fm,Δν)/δPp(fm)':r'H(f_m,\Delta\nu)=\frac{\delta P_s(f_m,\Delta\nu)}{\delta P_p(f_m)}',
 'h(τ,Δν)=IFTfm[H];  z=cτ/(2ng)':r'\begin{aligned}h(\tau,\Delta\nu)&=\mathcal F_{f_m}^{-1}[H(f_m,\Delta\nu)],\\z&=\frac{c\tau}{2n_g},\qquad\Delta z\simeq\frac{c}{2n_gB_m},\qquad L_{\mathrm{ua}}\simeq\frac{c}{2n_g\delta f_m}.\end{aligned}',
 'ν(t)=ν0+Δf sin(2πfmt);  νs(t)=ν(t)-Δν':r'\nu(t)=\nu_0+\Delta f\sin(2\pi f_mt),\qquad\nu_s(t)=\nu(t)-\Delta\nu',
 'δνlocal(z,t)=Δν+ν(t-τp(z))-ν(t-τs(z))':r'\delta\nu_{\mathrm{local}}(z,t)=\Delta\nu+\nu(t-\tau_p(z))-\nu(t-\tau_s(z))',
 'dpeak≈c/(2ngfm);  Δz ∝ 1/(fm Δf)':r'd_{\mathrm{peak}}\simeq\frac{c}{2n_gf_m},\qquad\Delta z\propto\frac1{f_m\Delta f}',
 'νm=ν0+m δν;  Bp,m(t)=a(t)exp(i2πνmt)':r'\nu_m=\nu_0+m\delta\nu,\qquad B_{p,m}(t)=a(t)e^{i2\pi\nu_mt}',
 'z=c(t-t0)/(2ng);  S(z,νm)=local Rayleigh signature':r'z=\frac{c(t-t_0)}{2n_g},\qquad S(z,\nu_m):\text{ local Rayleigh signature}',
 'Δεfiber=(q-KT ΔT)/Kε':r'\Delta\varepsilon_{\mathrm{fiber}}=\frac{q-K_T\Delta T}{K_\varepsilon}',
}

COMPONENTS = {
 'nll':r'B_0(t)=\sqrt{P_0}\,e^{i[2\pi\nu_0t+\phi_L(t)]}', 'ld':r'B_1(t)=\sqrt{P_0}\,a(t)',
 'tls':r'\nu(t)=\nu_0+\kappa t', 'iso':r'P_{\mathrm{forward}}=T_{\mathrm{iso}}P_{\mathrm{in}},\qquad T_{\mathrm{reverse}}\ll T_{\mathrm{iso}}',
 'splitter':r'P_1\simeq\eta P_{\mathrm{in}},\qquad P_2\simeq(1-\eta)P_{\mathrm{in}}', 'coupler2_dk':r'\mathbf B_{\mathrm{out}}=\mathbf U_{2\times2}\mathbf B_{\mathrm{in}}',
 'cir':r'1\longrightarrow2,\qquad2\longrightarrow3', 'edfa':r'P_{\mathrm{out}}\simeq G P_{\mathrm{in}}+P_{\mathrm{ASE}}',
 'bpf':r'B_{\mathrm{out}}(\nu)=H_{\mathrm{opt}}(\nu)B_{\mathrm{in}}(\nu)', 'im':r'B_{\mathrm{pulse}}(t)=a(t)B_0(t)',
 'iq':r'\nu_s=\nu_p-\Delta\nu', 'pc':r'\mathbf B_{\mathrm{out}}=\mathbf J_{\mathrm{PC}}\mathbf B_{\mathrm{in}}',
 'fiber':r't_{\mathrm{return}}\simeq\frac{2n_gz}{c}', 'delay':r'\tau_{\mathrm{arm}}=\frac{n_gL_{\mathrm{arm}}}{c}',
 'pd':r'i=\mathcal R P+b,\qquad V=Z_T*i', 'bpd':r'i_{\mathrm{diff}}=\mathcal R(P_+-P_-)',
 'adc':r'V[k]=V(t_0+k\Delta t_{\mathrm{ADC}})', 'awg':r'V_{\mathrm{drive}}(t)=\text{programmed waveform}',
 'dds':r'f_{\mathrm{RF}}=\text{programmed frequency}', 'ld_driver':r'\nu_{\mathrm{laser}}=f(I,T_{\mathrm{laser}})',
 'bias':r'V_{\mathrm{MZ}}=V_{\mathrm{bias}}+V_{\mathrm{drive}}', 'fpga':r'\widehat{\mathbf h}=\mathbf D\mathbf y',
 'computer':r'\text{observable}\longrightarrow\text{calibration}\longrightarrow\text{uncertainty}',
 'wdm':r'P_{\mathrm S}=P_{\mathrm{back}}|H_{\mathrm S}|^2,\qquad P_{\mathrm{AS}}=P_{\mathrm{back}}|H_{\mathrm{AS}}|^2',
 'apd':r'i_j=\mathcal R_j P_j+b_j', 'switch':r'\operatorname{port}(t)\in\{A,B\}',
 'bath':r'T(z\in Z_{\mathrm{ref}})=T_{\mathrm{ref}}', 'rtd':r'T_{\mathrm{ref}}\pm u_{\mathrm{ref}}',
 'spad':r'N_j\simeq\eta_j\Phi_jt_m+b_j', 'timetag':r'z=\frac{c(t_{\mathrm{arrival}}-t_0)}{2n_g}',
 'vna':r'H=|H|e^{i\phi}', 'fm_driver':r'\nu(t)=\nu_0+\Delta f\sin(2\pi f_mt)',
}

MACROS = {'\\R':r'\mathcal R','\\Hh':r'\mathcal H_T','\\LPF':r'\operatorname{LPF}','\\unwrap':r'\operatorname{unwrap}','\\atan':r'\operatorname{atan2}'}
